config/routes.rb
Myapp::Application.routes.draw do
  resources :watches do
    get 'unfulfilled', :on => :collection
  end

  resources :users do
    get 'watches', :on => :member
    post 'find_by_name', :on => :collection
  end

  get "home/index"

root to: 'home#index'

end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :watches
	validates :rating,
		numericality: {greater_than_or_equal_to: 0,
						less_than_or_equal_to: 5}
end

app/models/watch.rb
class Watch < ActiveRecord::Base
	belongs_to :user
	after_save { if !self.watcher_id 
					self.update_column(:status, "Unfulfilled Watch")
				 elsif self.watcher_id and !self.start_time
				 	self.update_column(:status, "Accepted Watch")
				 elsif self.start_time and !self.end_time
				 	self.update_column(:status, "In-progress Watch")
				 else
				 	self.update_column(:status, "Finished Watch")
				 end
			   }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter  :verify_authenticity_token
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # GET /users/1/watches
  def watches
    @watches = Watch.where(user_id: params[:id])
    render json: @watches, status: :ok
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /users/find_by_name
  def find_by_name
    if(found = User.find_by(name: params[:name]))
      render json: found, status: :ok
    else
      created = User.new(name: params[:name], rating: 4)
      created.save
      render json: created, status: :ok
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :rating)
    end
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController
  skip_before_filter  :verify_authenticity_token
  before_action :set_watch, only: [:show, :edit, :update, :destroy]

  # GET /watches
  # GET /watches.json
  def index
    @watches = Watch.all
  end

  # GET /watches/1
  # GET /watches/1.json
  def show
  end

  # GET /watches/new
  def new
    @watch = Watch.new
  end

  # GET /watches/1/edit
  def edit
  end

  # GET /watches/unfulfilled
  def unfulfilled
    @watches = Watch.where(status:"Unfulfilled Watch")
    render json: @watches, status: :ok
  end

  # POST /watches
  # POST /watches.json
  def create
    @watch = Watch.new(watch_params)

    respond_to do |format|
      if @watch.save
        format.html { redirect_to @watch, notice: 'Watch was successfully created.' }
        format.json { render action: 'show', status: :created, location: @watch }
      else
        format.html { render action: 'new' }
        format.json { render json: @watch.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /watches/1
  # PATCH/PUT /watches/1.json
  def update
    respond_to do |format|
      if @watch.update(watch_params)
        format.html { redirect_to @watch, notice: 'Watch was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @watch.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /watches/1
  # DELETE /watches/1.json
  def destroy
    @watch.destroy
    respond_to do |format|
      format.html { redirect_to watches_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_watch
      @watch = Watch.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def watch_params
      params.permit(:user_id, :user_name, :watcher_id, :watcher_name, :lat, :lng, :location_description, :location_picture, 
		    :requested_minutes, :start_time, :end_time, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/watches_helper.rb
module WatchesHelper
end

app/views/home/index.html.erb
<style type="text/css" media="screen">
      body {
	text-align:center;
        margin: 0;
        margin-bottom: 25px;
        padding: 0;
        background-color: #f0f0f0;
        font-family: "Lucida Grande", "Bitstream Vera Sans", "Verdana";
        font-size: 13px;
        color: #333;
      }

      h1 {
        font-size: 28px;
        color: #000;
      }

</style>
<h1 align="center">DigitalOcean Rails Application</h1>
<img src="assets/rails.png" align="center"><br/>
<p>This file is located in /home/rails/app/views/home/index.html.erb</p>

Your application root is located in: <%= Rails.root.to_s %><br>

Ruby version: <%= RUBY_VERSION %><br>

Rails version: <%= Rails.version %><br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DigitalOcean Rails Application</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Rating</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.rating %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @user.rating %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/watches/_form.html.erb
<%= form_for(@watch) do |f| %>
  <% if @watch.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@watch.errors.count, "error") %> prohibited this watch from being saved:</h2>

      <ul>
      <% @watch.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :watcher_id %><br>
    <%= f.number_field :watcher_id %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.number_field :lat %>
  </div>
  <div class="field">
    <%= f.label :lng %><br>
    <%= f.number_field :lng %>
  </div>
  <div class="field">
    <%= f.label :location_description %><br>
    <%= f.text_field :location_description %>
  </div>
  <div class="field">
    <%= f.label :location_picture %><br>
    <%= f.text_field :location_picture %>
  </div>
  <div class="field">
    <%= f.label :requested_minutes %><br>
    <%= f.time_select :requested_minutes %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br>
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br>
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/watches/edit.html.erb
<h1>Editing watch</h1>

<%= render 'form' %>

<%= link_to 'Show', @watch %> |
<%= link_to 'Back', watches_path %>

app/views/watches/index.html.erb
<h1>Listing watches</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Watcher</th>
      <th>Lat</th>
      <th>Lng</th>
      <th>Location description</th>
      <th>Location picture</th>
      <th>Requested lot</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Status</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @watches.each do |watch| %>
      <tr>
        <td><%= watch.user_id %></td>
        <td><%= watch.watcher_id %></td>
        <td><%= watch.lat %></td>
        <td><%= watch.lng %></td>
        <td><%= watch.location_description %></td>
        <td><%= watch.location_picture %></td>
        <td><%= watch.requested_minutes %></td>
        <td><%= watch.start_time %></td>
        <td><%= watch.end_time %></td>
        <td><%= watch.status %></td>
        <td><%= link_to 'Show', watch %></td>
        <td><%= link_to 'Edit', edit_watch_path(watch) %></td>
        <td><%= link_to 'Destroy', watch, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Watch', new_watch_path %>

app/views/watches/new.html.erb
<h1>New watch</h1>

<%= render 'form' %>

<%= link_to 'Back', watches_path %>

app/views/watches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @watch.user_id %>
</p>

<p>
  <strong>Watcher:</strong>
  <%= @watch.watcher_id %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @watch.lat %>
</p>

<p>
  <strong>Lng:</strong>
  <%= @watch.lng %>
</p>

<p>
  <strong>Location description:</strong>
  <%= @watch.location_description %>
</p>

<p>
  <strong>Location picture:</strong>
  <%= @watch.location_picture %>
</p>

<p>
  <strong>Requested lot:</strong>
  <%= @watch.requested_minutes %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @watch.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @watch.end_time %>
</p>

<p>
  <strong>Status:</strong>
  <%= @watch.status %>
</p>

<%= link_to 'Edit', edit_watch_path(@watch) %> |
<%= link_to 'Back', watches_path %>